# Global settings
timezone: Europe/Berlin

# Site settings
title: RuppertDesign
email: post@ruppertdesign.de
description: "TODO Description"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty

sass:
    style: :compressed
