# Global settings
timezone: Europe/Berlin
exclude: [README.md, Makefile, guidlines.md, tools, vendor]
include: [_redirects]

# Site settings
title: RUPPERTdesign – starkes Holzwerk!
email: info@ruppertdesign.de
description: RUPPERTdesign – starkes Holzwerk! Sie suchen nach einem besonderen Möbelstück aus Holz? RUPPERTdesign fertigt es Ihnen - praktisch, hochwertig, geradlinig, persönlich!
baseurl: ""
url: "https://www.ruppertdesign.de"

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: compressed

# Holzwerke Categories/Tags
holzwerke_tags:
  geschenke: "Geschenke"
  garderobe: "Garderoben"
  tische: "Tische"
  schraenke: "Schränke"
  wohnen: "Wohnen"
  kueche: "Küche"


# Schlüesselanhänger Categories/Tags
schluesselanhaenger_tags:
  geschenke: "Geschenke"
  hotel: "Hotels"
  hz: "Hochzeit"
  werbung: "Werbung"
  b2b: "B2B"  
 