# Global settings
timezone: Europe/Berlin
exclude: [README.md, Makefile]

# Site settings
title: RUPPERTdesign
email: info@ruppertdesign.de
description: "TODO Description"
baseurl: ""
url: "http://ruppertdesign.de"

# Build settings
markdown: kramdown
permalink: pretty

sass:
    style: compressed
