# Global settings
timezone: Europe/Berlin
exclude: [README.md, Makefile, guidlines.md, tools, vendor]

# Site settings
title: RUPPERTdesign – starkes Holzwerk!
email: info@ruppertdesign.de
description: RUPPERTdesign – starkes Holzwerk! Sie suchen nach einem besonderen Möbelstück aus Holz? RUPPERTdesign fertigt es Ihnen - praktisch, hochwertig, geradlinig, persönlich!
baseurl: ""
url: "https://www.ruppertdesign.de"

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: compressed

# Holzwerke Categories/Tags
holzwerke_tags:
  tische: "Tische"
  schraenke: "Schränke & Regale"
  wohnen: "Wohnen"
  kueche: "Küche"
  geschenke: "Geschenke"
  b2b: "B2B"
