# Global settings
timezone: Europe/Berlin
exclude: [README.md, Makefile]

# Site settings
title: RUPPERTdesign
email: info@ruppertdesign.de
description: RUPPERTdesign – starkes Holzwerk! Sie suchen nach einem besonderen Möbelstück aus Holz? RUPPERTdesign fertigt es Ihnen - praktisch, hochwertig, geradlinig, persönlich!
baseurl: ""
url: "http://ruppertdesign.de"

# Build settings
markdown: kramdown
permalink: pretty

sass:
    style: compressed
